Fix tag fetching

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -15,9 +15,10 @@ jobs:
         id: get-tag
         run: |
           URL="https://hub.docker.com/v2/namespaces/minaprotocol/repositories/mina-daemon/tags?page_size=25"
-          #URL=https://gist.githubusercontent.com/akoptelov/56c1ff38a0d0b1a82eec1a74f2fed856/raw/4a17548743f49827bd43215056493f8e870b90ba/tags.json
-          JQ='.results | sort_by(.last_updated) | .[] | select(.name | endswith("focal-mainnet")) | .name'
-          echo "tag=$(curl "$URL" | jq -cr "$JQ" | head -n 1)" >> $GITHUB_OUTPUT
+          JQ='.results | sort_by(.last_updated) | .[] | select(.name | endswith("focal-berkeley")) | .name'
+          TAG=$(curl "$URL" | jq -cr "$JQ" | head -n 1)
+          [ -n "$TAG" ] || { echo "Cannot get latest focal-berkeley tag"; exit 1; }
+          echo "tag=$TAG" >> $GITHUB_OUTPUT
       - run: echo "Using minaprotocol/mina-daemon:${{ steps.get-tag.outputs.tag }}"
 
       - name: Checkout Mina
